"""add userprofile and fix books scehema 

Revision ID: ef9e733d3252
Revises: 
Create Date: 2026-04-23 23:14:18.546877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9e733d3252'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_bio'), 'user_profiles', ['bio'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_phone_number'), 'user_profiles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_profiles_profile_picture'), 'user_profiles', ['profile_picture'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('image', sa.String(), nullable=True))
    op.add_column('books', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=True))
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.drop_index(op.f('ix_books_cover_image'), table_name='books')
    op.create_index(op.f('ix_books_description'), 'books', ['description'], unique=False)
    op.create_index(op.f('ix_books_image'), 'books', ['image'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_language'), 'books', ['language'], unique=False)
    op.create_index(op.f('ix_books_pages'), 'books', ['pages'], unique=False)
    op.create_index(op.f('ix_books_year'), 'books', ['year'], unique=False)
    op.drop_column('books', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_books_year'), table_name='books')
    op.drop_index(op.f('ix_books_pages'), table_name='books')
    op.drop_index(op.f('ix_books_language'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_image'), table_name='books')
    op.drop_index(op.f('ix_books_description'), table_name='books')
    op.create_index(op.f('ix_books_cover_image'), 'books', ['cover_image'], unique=False)
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'pages')
    op.drop_column('books', 'language')
    op.drop_column('books', 'year')
    op.drop_column('books', 'image')
    op.drop_column('books', 'description')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_picture'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_phone_number'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_bio'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
